services:
  vpn:
    build: .
    cap_add:
      - NET_ADMIN
    restart: always
    ports:
      - 53:53
      - 443:443
      - 992:992
      - 1194:1194/udp
      - 5555:5555
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/udp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./.docker/data:/mnt"
      - "./.docker/log:/root/server_log"
      - "./.docker/packetlog:/root/packet_log"
      - "./.docker/securitylog:/root/security_log"